# Copyright (c) 2020-2021 Advanced Robotics at the University of Washington <robomstr@uw.edu>
#
# This file is part of Taproot.
#
# Taproot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Taproot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Taproot.  If not, see <https://www.gnu.org/licenses/>.

default:
  image: aruw/mcb-2020-gitlab-ci:2021-06-02.1

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  NUM_JOBS: 4
  ADDITIONAL_CI_BUILD_ARGS: -j${NUM_JOBS} additional-ccflags=-Werror

.default_only: &default_only
  - merge_requests
  - master
  - develop
  - schedules

.verification_only: &verification_only
  - merge_requests
  - master
  - develop

.verification_except: &verification_except
  - schedules 

stages:
  - Initial Verification
  - Generate Test Project
  - Build all Targets
  - Deploy Pages

before_script:
  - python3 -V # Print out python version for debugging

# Initial verification

"Clang Format":
  stage: Initial Verification
  needs: []
  script:
    - python3 /run-clang-format.py --clang-format-executable clang-format-10 -r src/ test/
  only: *verification_only
  except: *verification_except

"Policy Checks":
  stage: Initial Verification
  needs: []
  script:
    - python3 ./taproot-scripts/check_singleton_drivers.py DoNotUse_getDrivers -p src
    - python3 ./taproot-scripts/check_license_headers.py
        -p Taproot
        -o 'Advanced Robotics at the University of Washington'
        -i './modm/**/*'
          './test-project/taproot/**/*'
          './taproot-scripts/**/*'
          './**/__init__.py'
          './docs/**/*.py'
          './src/tap/algorithms/MahonyAHRS.*'
          './ext/**/*'
    - python3 ./taproot-scripts/check_header_guard.py
        src test
        -p TAPROOT_
        -i src/tap/algorithms/MahonyAHRS.h
            src/tap/display/sh1106_impl.hpp
            src/tap/display/sh1106_mock_impl.hpp
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  only: *verification_only
  except: *verification_except

.run_lbuild:
  script:
    - cd test-project && lbuild build && cd ..
  artifacts:
    paths:
      - test-project

.type_a_config_dependencies:
  needs: ["Type A: Generate Test Project"]
  dependencies: ["Type A: Generate Test Project"]

.type_c_config_dependencies:
  needs: ["Type C: Generate Test Project"]
  dependencies: ["Type C: Generate Test Project"]

.mcb_build:
  stage: "Build all Targets"
  only: *default_only
  script:
    - cd test-project
    - scons build $ADDITIONAL_CI_BUILD_ARGS

.sim_build:
  stage: "Build all Targets"
  only: *default_only
  script:
    - cd test-project
    - scons build-sim profile=fast $ADDITIONAL_CI_BUILD_ARGS

.tests_build:
  stage: "Build all Targets"
  only: *default_only
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script:
    - cd test-project
    - scons run-tests-gcov profile=fast $ADDITIONAL_CI_BUILD_ARGS
    - valgrind --leak-check=full --error-exitcode=1 --show-leak-kinds=all build/tests/scons-fast/test-project-tests.elf
    - cd .. && gcovr -g --xml > cobertura.xml
    - 'sed -i "s;filename=\"taproot/;filename=\";g" cobertura.xml'
    - python3 ./taproot-scripts/shift_cobertura_line_numbers.py --shift-lines -4 --package-names 'taproot.(src|test).*' --out-file cobertura.xml
  coverage: '/\s+Total:\|(\d+.\d+\%).+\|.+\|.+/'
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-tests"
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml
    expire_in: 2 weeks

"Type A: Generate Test Project":
  needs: []
  only: *default_only
  stage: Generate Test Project
  extends:
    - .run_lbuild
  variables:
    BOARD_TYPE: type_a

"Type C: Generate Test Project":
  needs: []
  stage: Generate Test Project
  only: *default_only
  extends:
    - .run_lbuild
  before_script:
    - cd test-project
    - sed -i '/<!-- For RoboMaster Development Board Type A -->/,/<!-- End For RoboMaster Development Board Type A -->/c\' project.xml
    - sed -i '/<!-- For RoboMaster Development Board Type C --> <!--/c\' project.xml
    - sed -i '/--> <!-- End For RoboMaster Development Board Type C -->/c\' project.xml
    - cd ..
  variables:
    BOARD_TYPE: type_c

# Type A CI
"Type A: MCB Build":
  extends:
    - .type_a_config_dependencies
    - .mcb_build

"Type A: Sim Build":
  extends:
    - .type_a_config_dependencies
    - .sim_build

"Type A: Tests Build":
  extends:
    - .type_a_config_dependencies
    - .tests_build

# Type C CI
"Type C: MCB Build":
  extends:
    - .type_c_config_dependencies
    - .mcb_build

"Type C: Sim Build":
  extends:
    - .type_c_config_dependencies
    - .sim_build

"Type C: Tests Build":
  extends:
    - .type_c_config_dependencies
    - .tests_build

# Pages deploy

"Generate Docs":
  image: alpine
  needs: []
  stage: Deploy Pages
  before_script:
    - apk update
    - apk add py-pip python3-dev
    - apk add make
    - apk add --no-cache g++ gcc libxml2-dev libxslt-dev
    - pip3 install lxml
    - pip3 install sphinx breathe exhale
    - pip install sphinx_rtd_theme
    - apk add doxygen
  script:
    - cd docs && make html
    - mv _build/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - develop
    - merge_requests
  environment:
    name: "docs preview ${CI_COMMIT_REF_SLUG}"
    url: "https://aruw.gitlab.io/-/controls/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/public/index.html"

pages:
  image: alpine
  needs: ["Generate Docs"]
  dependencies: ["Generate Docs"]
  stage: Deploy Pages
  before_script:
    - "true"
  script: "true"
  artifacts:
    paths:
      - public
  only:
    - develop
  except:
    - schedules
